name: Tumor/normal calling with priors
desc: |
  This scenario configures Varlociraptor to perform tumor/normal calling. The model is configured with prior assumptions about mutation rate and heterozygosity.


