SCENARIOS = glob_wildcards("../../../scenarios/{scenario}/scenario.yaml").scenario


rule all:
    input:
        expand("../{scenario}.md", scenario=SCENARIOS)


rule render_scenario:
    input:
        scenario="../../../scenarios/{scenario}/scenario.yaml",
        meta="../../../scenarios/{scenario}/meta.yaml",
        template="resources/template.md.jinja",
    output:
        "../{scenario}.md"
    conda:
        "envs/render.yaml"
    script:
        "scripts/render.py"