name: Tumor-only calling without priors
desc: |
  This scenario configures Varlociraptor to perform tumor-only calling.
  Contamination of the tumor sample by normal cells is specified.

  With such a scenario, even when no aligned reads from a separate normal sample are provided, Varlociraptor can still calculate the probabilities for the defined events.
  Naturally, whenever the observed reads do not allow to decide, both probabilities will become accordingly weak.
  This is e.g. the case for an observed allele frequency of 0.5, which in this scenario can be either a somatic variant with allele frequency 1/3, or a heterozygous germline variant.
  If the observed allele frequency is 1.0 though, it is clear that the variant has to be germline, since a somatic variant could occur at a frequency of 0.75 at most (because of the contamination).
  Similarly, an observed allele frequency far away from 0.5 and 1.0 indicates a tendency towards a somatic variant, which will again be properly reflected in the event probabilities.

  Since there will be often ambiguity between germline and somatic events (which, as intended, properly reflects the uncertainty in the data), one should control the FDR only jointly on the three events defined here, not on one of them.
  For the resulting filtered set of variants, judgement about interpretation and following actions should then be made individually, with the three probabilities in mind.