name: Tumor/normal/relapse calling with priors
desc: |
  This scenario configures Varlociraptor to perform tumor/normal/relapse calling. The model is configured with prior assumptions about mutation rate and heterozygosity.
plot-prior:
  samples:
    - relapse
  contigs:
    - 1
